// DO NOT MODIFY. This file is automatically generated by Firebase Studio.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: "AIzaSyDqAl3FbS9kl50JWwHBmlcci9-wq-kEG90",
  authDomain: "certguard-lite.firebaseapp.com",
  projectId: "certguard-lite",
  storageBucket: "certguard-lite.firebasestorage.app",
  messagingSenderId: "742712155958",
  appId: "1:742712155958:web:d8aafeabafdb9c1cf2dd97",
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);

export { app, db };
