// DO NOT MODIFY. This file is automatically generated by Firebase Studio.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  apiKey: " ",
  authDomain: "certguard-lite.firebaseapp.com",
  projectId: "certguard-lite",
  storageBucket: "certguard-lite.firebasestorage.app",
  messagingSenderId: " ",
  appId: " ",
};

// Initialize Firebase
const app = getApps().length ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);

export { app, db };
